xcodeproj 'FunctionalExtensions-ObjC'
platform :ios, '6.0'

target 'FunctionalExtensions-ObjCTests', :exclusive => false do
	# pod 'Kiwi', '~> 2.3.0'
        pod 'Kiwi', :head
end

pod 'FunctionalExtensions-ObjC', :path => '..'
